---
- name: Ansible Playbook to Deploy petclinic app
  hosts: tag_appserver
  vars:
   build_number: "{{ build_number }}"
  tasks:
    - name: remove the app if exists
      file:
       state: absent
       path: /opt/spring-petclinic-{{ build_number }}.jar 

    - name: Download Artifacts from Jfrog
      get_url:
       url: http://ec2-3-238-179-255.compute-1.amazonaws.com:8082/artifactory/petclinic/dev/spring-petclinic-{{ build_number }}.jar
       dest: /opt
       url_username: admin
       url_password: "{{ password }}" 

    - name: Install Java
      yum: name={{item}} state=latest
      with_items:
       - java-1.8.0-openjdk
   
    - name: Get running processes
      shell: "ps -ef | grep -i spring | awk '{print $2}'"
      register: running_processes
      ignore_errors: yes 

    - name: Kill running processes
      shell: "kill -9  {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"
      ignore_errors: yes

    - name: running the app
      shell: "java -jar /opt/spring-petclinic-{{ build_number }}.jar"
     
